# Generated by Django 5.0.6 on 2024-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_posts_privacy_story_privacy_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
