# Generated by Django 5.0.6 on 2024-06-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_friendrequests_requested'),
        ('app_users', '0002_profile_registered_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app_users.profile'),
        ),
    ]
