# Generated by Django 5.0.6 on 2024-06-22 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0006_alter_friends_author'),
        ('app_users', '0002_profile_registered_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker_person', to='app_users.profile'),
        ),
    ]
