# Generated by Django 5.0.6 on 2024-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0007_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='own_like',
            field=models.BooleanField(default=False),
        ),
    ]
