# Generated by Django 5.0.6 on 2024-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0008_like_own_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='own_like',
        ),
        migrations.AddField(
            model_name='postimage',
            name='own_like',
            field=models.BooleanField(default=False),
        ),
    ]
