# Generated by Django 5.0.6 on 2024-07-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0009_remove_like_own_like_postimage_own_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='own_like',
        ),
    ]
