# Generated by Django 5.0.6 on 2024-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profile_registered_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover.png', null=True, upload_to='cover_pic/'),
        ),
    ]
