# Generated by Django 5.0.6 on 2024-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_address_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('in_a_relation', 'In a relation')], default='single', max_length=20),
        ),
    ]
